Homework # 1 CompSci X 433.6

In [915]:
from os.path import join, dirname, abspath
import xlrd
import math
import numpy as np
import matplotlib.pyplot as plt

In [916]:
Hbins=6

In [917]:
import pandas as pd
xl = pd.ExcelFile("Assignment_2_Data_and_Template.xlsx")
df = xl.parse(xl.sheet_names[0])
df.head()


Sex  Height  HandSpan
0  Female    68.0      21.5
1    Male    71.0      23.5
2    Male    73.0      22.5
3  Female    64.0      18.0
4    Male    68.0      23.5

In [918]:
A1 = df.reset_index().values
A1T=np.transpose(A1)
A = np.transpose(A1T[1:4])
print(A[:5])

[['Female' 68.0 21.5]
 ['Male' 71.0 23.5]
 ['Male' 73.0 22.5]
 ['Female' 64.0 18.0]
 ['Male' 68.0 23.5]]


In [919]:
print(A.shape)

(167, 3)


In [920]:
numbin=math.ceil(math.sqrt(A.shape[0]/2 + 1))
print(numbin)


10


In [921]:
print(A[1])

['Male' 71.0 23.5]


In [922]:
AT = np.transpose(A)
S = AT[0]
print(S.shape)

(167,)


In [923]:
def GetNums(S):
    Fnum=0
    Mnum=0
    for i in range(0,S.shape[0]):
        if S[i]=='Female':
            Fnum+=1;
        if S[i]=='Male':
            Mnum+=1;
    return Fnum, Mnum

In [924]:
def GetSplitData(S,D,fnum,mnum):
    Fdata=np.zeros((2,fnum))
    Mdata=np.zeros((2,mnum))
    Fidx=0
    Midx=0
    for i in range(0,S.shape[0]):
        if S[i]=='Female':
            Fdata[0][Fidx]=D[1][i];
            Fdata[1][Fidx]=D[2][i];
            Fidx+=1;
        if S[i]=='Male':
            Mdata[0][Midx]=D[1][i];
            Mdata[1][Midx]=D[2][i];
            Midx+=1;
    return Fdata, Mdata

In [925]:
AT = np.transpose(A)
S = AT[0]
HT = AT[1]
HS = AT[2]
Fnum, Mnum = GetNums(S)
HTmin=np.min(HT)
HTmax=np.max(HT)
HSmin=np.min(HS)
HSmax= np.max(HS)

FD, MD = GetSplitData(S,AT,Fnum,Mnum)

FHT=FD[0]
FHS=FD[1]
HTFmin=np.min(FHT)
HTFmax=np.max(FHT)
HSFmin=np.min(FHS)
HSFmax= np.max(FHS)

HTFmean=np.mean(FHT)
HSFmean=np.mean(FHS)
HTFstd=np.std(FHT,ddof=1)
HSFstd=np.std(FHS,ddof=1)

MHT=MD[0]
MHS=MD[1]
HTMmin=np.min(MHT)
HTMmax=np.max(MHT)
HSMmin=np.min(MHS)
HSMmax= np.max(MHS)

HTMmean=np.mean(MHT)
HSMmean=np.mean(MHS)
HTMstd=np.std(MHT,ddof=1)
HSMstd=np.std(MHS,ddof=1)

print("Num Females = {}, Num Males = {}".format(Fnum,Mnum))
print("Height: Min = {}, Max = {}".format(HTmin,HTmax))
print("HandSpan: Min = {}, Max = {}".format(HSmin,HSmax))

print("Female: Height: Min = {}, Max = {} : HandSpan: Min = {}, Max = {}".format(HTFmin,HTFmax,HSFmin,HSFmax))
print("Female: Height: Mean = {}, Std = {} : HandSpan: Mean = {}, Std = {}".format(HTFmean,HTFstd,HSFmean,HSFstd))
print("Male: Height: Min = {}, Max = {} : HandSpan: Min = {}, Max = {}".format(HTMmin,HTMmax,HSMmin,HSMmax))
print("Male: Height: Mean = {}, Std = {} : HandSpan: Mean = {}, Std = {}".format(HTMmean,HTMstd,HSMmean,HSMstd))


Num Females = 89, Num Males = 78
Height: Min = 57.0, Max = 78.0
HandSpan: Min = 16.0, Max = 25.5
Female: Height: Min = 57.0, Max = 72.0 : HandSpan: Min = 16.0, Max = 23.0
Female: Height: Mean = 65.25280898876404, Std = 2.7852835618511596 : HandSpan: Mean = 19.60112359550562, Std = 1.3254068313697012
Male: Height: Min = 66.0, Max = 78.0 : HandSpan: Min = 18.0, Max = 25.5
Male: Height: Mean = 71.28846153846153, Std = 2.6622898438726037 : HandSpan: Mean = 22.30128205128205, Std = 1.4354956236950658


In [926]:
HTbins = math.ceil(HTmax - HTmin + 1)
HSbins = math.ceil(2*HSmax - 2*HSmin + 1)
print("HTbins = {}, HSbins = {}".format(HTbins,HSbins))

HTbins = 22, HSbins = 20


In [927]:
def Build1HistogramClassifier(HT,HS,S,Hbins):
    HTmin=np.min(HT)-1
    HTmax=np.max(HT)
    if (HTmax == math.ceil(HTmax)):
        HTmax = HTmax+1
    else:
        HTmax = math.ceil(HTmax)
    HSmin=np.min(HS)-0.5
    HSmax=np.max(HS)
    if (HSmax == math.ceil(HSmax)):
        HSmax = HSmax+0.5
    else:
        HSmax = math.ceil(HSmax)

    HF=np.zeros((Hbins,Hbins))
    HM=np.zeros((Hbins,Hbins))
    
    Hmins=np.array([HTmin,HSmin])
    Hwidths=np.array([(HTmax-HTmin)/Hbins,(HSmax-HSmin)/Hbins])
    
    for i in range(0,S.size):
        bx=(np.round(((Hbins-1)*(HT[i]-HTmin)/(HTmax-HTmin)))).astype('int32')
        by=(np.round(((Hbins-1)*(HS[i]-HSmin)/(HSmax-HSmin)))).astype('int32')
        if S[i]=='Female':
            HF[bx][by]+=1;
        else:
            HM[bx][by]+=1;
    return HF,HM,Hmins,Hwidths

In [928]:

HF,HM,Hmin,Hwd = Build1HistogramClassifier(HT,HS,S,Hbins)

In [929]:
print(Hmin,Hwd)


[ 56.   15.5] [ 3.83333333  1.75      ]


In [930]:
print(HF)

[[  1.   0.   0.   0.   0.   0.]
 [  0.   8.   4.   0.   0.   0.]
 [  1.  11.  36.   9.   0.   0.]
 [  0.   2.  10.   6.   1.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]


In [931]:
print(HM)

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   1.   7.   1.   0.]
 [  0.   1.   7.  24.   9.   0.]
 [  0.   0.   1.   8.  18.   0.]
 [  0.   0.   0.   0.   0.   1.]]


In [932]:
print(Hmin[1],(Hmin[1]+Hwd[1]*(Hbins-1)), Hwd[1])
print(Hmin[0],(Hmin[0]+Hwd[0]*(Hbins-1)), Hwd[0])

15.5 24.25 1.75
56.0 75.1666666667 3.83333333333


In [933]:
histcol=np.arange((Hmin[1]+(0.5*Hwd[1])),(Hmin[1]+(Hwd[1]*((Hbins)+0.4))), Hwd[1])
histidx=np.arange((Hmin[0]+(0.5*Hwd[0])),(Hmin[0]+(Hwd[0]*((Hbins)+0.4))), Hwd[0])
print(histcol)
print(histidx)

[ 16.375  18.125  19.875  21.625  23.375  25.125]
[ 57.91666667  61.75        65.58333333  69.41666667  73.25        77.08333333]


In [934]:
dfhf = pd.DataFrame(HF,index=histidx,columns=histcol)
dfhm = pd.DataFrame(HM,index=histidx,columns=histcol)

In [935]:
writer = pd.ExcelWriter('output.xlsx')
dfhf.to_excel(writer,'FemaleHist')
dfhm.to_excel(writer,'MaleHist')
writer.save()

In [936]:
Fcov=np.cov(FD)
print("Covariance Matrix : Female")
print(Fcov)

Covariance Matrix : Female
[[ 7.75780452  1.65170135]
 [ 1.65170135  1.75670327]]


In [937]:
Mcov=np.cov(MD)
print("Covariance Matrix : Male")
print(Mcov)

Covariance Matrix : Male
[[ 7.08778721  1.80157343]
 [ 1.80157343  2.06064769]]


In [938]:
Fdet=np.linalg.det(Fcov)
Mdet=np.linalg.det(Mcov)
print("Determinant: Female = {} , male = {}".format(Fdet,Mdet))

Determinant: Female = 10.900043196726429 , male = 11.359765505057714


In [939]:
def BayesianProb(val, num, dimn, mean, cov):
    covinv = np.linalg.inv(cov)
    diff = val-mean
    p1 = np.dot(diff,covinv)
    diffT = np.transpose(diff)
    p2 = np.dot(p1,diffT)
    numerator = math.exp(-1*(p2/2))
    
    det=np.linalg.det(cov)
    detsqrt = math.sqrt(det)
    denominator = 2*math.pi*detsqrt
    
    v = numerator/denominator
    v = v*num
    return v


In [940]:
def HistProb(histf, histm, val, offset, width, bins): 
    nbin = val - offset
    bx=(np.round((bins-1)*(nbin[0])/(bins*width[0]))).astype('int32')
    by=(np.round((bins-1)*(nbin[1])/(bins*width[1]))).astype('int32')
    pb = (histf[bx,by]/(histf[bx,by] + histm[bx,by])) #height return 
    return pb


In [941]:
Fmean = np.array([[HTFmean,HSFmean]])
Mmean = np.array([[HTMmean,HSMmean]])

In [942]:
test = np.array([[69,17.5],[66,22],[70,21.5],[69,23.5]])
for i in range(0,4):
    TestA=np.array([[test[i][0],test[i][1]]])
    Hpb = HistProb(HF,HM,test[i],Hmin,Hwd,Hbins)
    Fpb = BayesianProb(TestA, Fnum, 2, Fmean, Fcov)
    Mpb = BayesianProb(TestA, Mnum, 2, Mmean, Mcov)
    FBcondP = Fpb / (Fpb + Mpb)
    print("For test data {}, Probability of Female: Histogram = {}, Bayesian = {}".format(TestA,Hpb,FBcondP))

For test data [[ 69.   17.5]], Probability of Female: Histogram = 0.6666666666666666, Bayesian = 0.8985362558122361
For test data [[ 66.  22.]], Probability of Female: Histogram = 0.5625, Bayesian = 0.6555792232463564
For test data [[ 70.   21.5]], Probability of Female: Histogram = 0.2, Bayesian = 0.19885721783198404
For test data [[ 69.   23.5]], Probability of Female: Histogram = 0.1, Bayesian = 0.056451796527341565
